version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: renting_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renting_usermanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - renting_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: renting_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@renting.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - renting_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  renting_network:
    driver: bridge
